### ISSUE TITLE
add whitelist by UUID in config

### ISSUE THREAD

**Issue by NukaExpress** [gekware/minecraft-server-hibernation#124]
Hey, I don't know why, but for some reason random players keep joining my server, causing the server to restart over and over again.
Is it possible to check if the player name/UUID is on the whitelist?
(I don't know how to add labels)

**Comment by gekigek99** [comment]
It could be a good feature to implement... I'm not sure that the UUID of the player is sent in the "join request" tho, I'll need to check.

Maybe it's possible to use the player name instead of the UUID.

**Comment by snaildos** [comment]
> It could be a good feature to implement... I'm not sure that the UUID of the player is sent in the "join request" tho, I'll need to check.
> 
> Maybe it's possible to use the player name instead of the UUID.

Very sure it is.

+1 on this

**Comment by gekigek99** [comment]
the whitelist feature was added here: c478b8ac20d8b00b717f7547fe19ef8c2a5e4511

The witelist supports both player name and IP, but not the player UUID.

**Comment by gekigek99** [comment]
@snaildos do you have some docs regarding how to extract player UUID during join request?

(if you like the rep please consider giving a star!)

**Comment by snaildos** [comment]
> @snaildos do you have some docs regarding how to extract player UUID during join request?
> 
> (if you like the rep please consider giving a star!)

No, I don't know how to extract it, I'm just pretty sure it gets sent.
Well done on the repo! I left a star. :3

**Comment by gekigek99** [comment]
> I'm just pretty sure it gets sent.

Yeah sure me too... but the problem is that it might get sent after the encryption and that would make things really hard... i'll need to do some research

**Comment by gekigek99** [comment]
Unfortunately UUID is sent after the connection is encrypted.

This means that it's much more difficult to capture it and allow clients based on their uuid to start the server.

I'm not saying that it wont be done in the future but for now there are more urgent problems to be solved

The start server whitelist for now supports playername and ip.

**Comment by Azarattum** [comment]
@gekigek99 is it possible to use build-in server's whitelist? If not, could you maybe add something like `"Whitelist": true` that would make msh lookup whitelisted names in server's `whitelist.json`?

**Comment by gekigek99** [comment]
@Azarattum 
I actually kept the 2 things separated on purpose since a server admin might want to have a list of people that can start the server and a list of people that can join the server.

But I guess I could add an other paramenter in config to mirror the ms whitelist json file. Can you open a new issue for that?

**Comment by Azarattum** [comment]
@gekigek99 I've opened a new issue as requested https://github.com/gekware/minecraft-server-hibernation/issues/163
