### ISSUE TITLE
"msh exit" command does not gracefully shutdown server

### ISSUE THREAD

**Issue by GabrielSerealia** [gekware/minecraft-server-hibernation#134]
And I just wanted to confirm if the "msh exit" command gracefully exists like ^C in 2.4.0
(After some testing the exit command doesn't appear to perform a graceful shutdown of the server, using ^C appears to gracefully shutdown)

**Comment by gekigek99** [comment]
This is probably the reason: in the input package `servctrl.ServTerm.Wg.Wait()`  is not called so msh does not wait for the server to exit.

https://github.com/gekware/minecraft-server-hibernation/blob/26ccf4a87390764adacfc9f3f9a3847933febbc5/lib/input/input.go#L69-L75

https://github.com/gekware/minecraft-server-hibernation/blob/26ccf4a87390764adacfc9f3f9a3847933febbc5/lib/progmgr/progmgr.go#L29-L57

**Comment by gekigek99** [comment]
fixed in 0a8093d9821ae882aac618da58a40e4f274b177a
