### ISSUE TITLE
(2.4.4) Problem: Server ships with Debug 1 and dosn´t log EULA Warning

### ISSUE THREAD

**Issue by BolverBlitz** [gekware/minecraft-server-hibernation#137]
Problem: Fresh install of MSH will just tell you

MINECRAFT SERVER IS STARTING!
MINECRAFT SERVER IS STOPPING!

No Information given. Took me quite some time to realize that the EULA is set to false (by default)

MSH should tell the user to accept the EULA first.
Either manualy or msh could await user input "yes" and then set EULA to true.

**Comment by gekigek99** [comment]
should msh be shipped with loglevel debug to 2?

**Comment by BolverBlitz** [comment]
Don´t know if thats the best solution

**Comment by gekigek99** [comment]
added in fb669544ee9a72928d9e3b7c69976366aefaf059

**Comment by BolverBlitz** [comment]
Minecraft 1.18 requires running the server with Java 17 or above. Download Java 17 (or above) from https://adoptium.net/

This should also be displayed, no matter the debug level (Aswell as response for Minecraft on next join) because not everyone lookes at consoles

**Comment by gekigek99** [comment]
should msh download java 17 and install it automagically? I dont think thats a good idea cause everyine has a different setup...

> This should also be displayed, no matter the debug level (Aswell as response for Minecraft on next join) because not everyone lookes at consoles

you mean while loading config just display a warning reminding people of installing java 17? or displayed where?

**Comment by BolverBlitz** [comment]
> you mean while loading config just display a warning reminding people of installing java 17? or displayed where?

No. The message should be displayed, diffrent minecraft versions need diffrent Java versions. Just log those errors out.
It helps nobody when you run msh and it just tells you
```sh
Minecraft Online
Minecraft Offline
Minecraft Online
Minecraft Offline
Minecraft Online
Minecraft Offline
....
```
You know, thats not helpfull.

**Comment by gekigek99** [comment]
displayed in terminal or when the client is joining the server? (I think it should only be displayed in terminal)

**Comment by BolverBlitz** [comment]
1. I would say terminal but also lock msh from starting and tell joining clients to look at msh terminal, ajust settings and restart msh.

2.

> Minecraft 1.18 requires running the server with Java 17 or above. Download Java 17 (or above) from https://adoptium.net/

**Comment by gekigek99** [comment]
Can i keep this issue open and close #97?

**Comment by gekigek99** [comment]
> Minecraft 1.18 requires running the server with Java 17 or above. Download Java 17 (or above) from https://adoptium.net/

I do i check if user java version is compatible with user minecraft server?

**Comment by BolverBlitz** [comment]
> Can i keep this issue open and close https://github.com/gekware/minecraft-server-hibernation/issues/97?
Sure

> I can do a string variable in servctrl that if set, it will warn clients with a message in handleclientsocket, preventing them joining in the server.
Sounds fine

> I do i check if user java version is compatible with user minecraft server?
No, because a lot are compatibale but some versions just perform better. Only tell users if it dosn´t work ie enoth

**Comment by gekigek99** [comment]
added in 2b87f482f2a0bd3ed11796fb55edcfb78b954aa4

for me it's working, what do you think?
