### ISSUE TITLE
MSH starts server while players are already playing (If Waterfall Proyx is used)

### ISSUE THREAD

**Issue by BolverBlitz** [gekware/minecraft-server-hibernation#144]
### Current Behavior (🐛 Bug)

Only seen this with Waterfall proxy.

If a player joins a MSH server, MSH will start minecraft.
Then if another player tryes to join, MSH will forward him to minecraft server running but also starts a new miencraft server that will fail because the port is used already

Log: (Debug Lv 3)
![grafik](https://user-images.githubusercontent.com/35345288/161964818-04450279-a285-41f5-b3e5-e94af92199e2.png)

### Expected Behavior

Don´t start the minecraft server when its already runnning

### Steps to Reproduce

Join a msh server 2 times.

### MSH-Version

2.4.6

### Operating system

Debian

### Minecraft Version

1.18.2

### Minecraft Server Software

Paper

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details.

**Comment by BolverBlitz** [comment]
Create Bungeecord and download Waterfall https://papermc.io/

**Comment by gekigek99** [comment]
![immagine](https://user-images.githubusercontent.com/53654579/168393282-7fd46ed0-e104-4be8-8b51-9c8588988371.png)

seems to be solved now, 
probably fixed in 6cc145c7387707144ec0ac4eca8d741812a328e1
