### ISSUE TITLE
1.18.2 update

### ISSUE THREAD

**Issue by UltraHispeed-Elite** [gekware/minecraft-server-hibernation#145]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Hello I was looking at this and was wondering if there is an 1.18 update on the way for this?

### Describe the solution you'd like.

Update to 1.18.2

**Comment by gekigek99** [comment]
In the provided config, the version is set to `1.17.1` but msh will automatically update it when the actual server version is found.

So just launch msh and try to connect to it and msh will automatically update its config.

_If you like this repo please give it a star_
