### ISSUE TITLE
[Question] Changing colors

### ISSUE THREAD

**Issue by PadowYT2** [gekware/minecraft-server-hibernation#149]
*as discord link is not working*
How can I make all colors normal and not gray? I see 2 lines
https://github.com/gekware/minecraft-server-hibernation/blob/e61f02af4638994582306a81babd78ffcee5114f/lib/servctrl/servctrl-cmd.go#L131
https://github.com/gekware/minecraft-server-hibernation/blob/e61f02af4638994582306a81babd78ffcee5114f/lib/servctrl/servctrl-cmd.go#L227

**Comment by gekigek99** [comment]
> as discord link is not working

Aaaarrrgghh why does it keep expiring even tho i set it to not expire

Set line: 
`errco.Logln(errco.LVL_C, "%s%s%s", errco.COLOR_GRAY, line, errco.COLOR_RESET)`

To:
`errco.Logln(errco.LVL_C, "%s", line)`

**Comment by PadowYT2** [comment]
> > as discord link is not working
> 
> Aaaarrrgghh why does it keep expiring even tho i set it to not expire
> 
> Set line:
> 
> ```go
> errco.Logln(errco.LVL_C, "%s%s%s", errco.COLOR_GRAY, line, errco.COLOR_RESET)
> ```
> 
> To:
> 
> ```go
> errco.Logln(errco.LVL_C, "%s", line)
> ```

Wait, in both lines?

**Comment by gekigek99** [comment]
Yes they are equal.

Remember to compile from dev branch.

If you like this repo please give it a star and share it with friends! It's very appreciated

**Comment by PadowYT2** [comment]
Mind sending the discord url? I have other questions

**Comment by PadowYT2** [comment]
@gekigek99?
