### ISSUE TITLE
Update for forge 1.18

### ISSUE THREAD

**Issue by eyhc1** [gekware/minecraft-server-hibernation#160]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Since 1.17 forge [get rid of server.jar](https://www.reddit.com/r/MinecraftForge/comments/rjovnl/comment/hp92se3/?utm_source=share&utm_medium=web2x&context=3). But this program still looking for a server.jar when starting, which makes it not compatible with the newer versions for forge servers. Insdead, they are now using bash scripts to start the server.

current config:
```
{
  "Server": {
    "Folder": "%SERVERPATH%\\paper 1.19",
    "FileName": "run.bat",
    "Protocol": "759",
    "Version": "Paper 1.19"
  },
  "Commands": {
    "StartServer": "java -Xmx1024M -Xms1024M -jar serverFileName nogui",
    "StopServer": "stop",
    "StopServerForce": "stop"
  },
  "Msh": {
    "CheckForUpdates": false,
    "Debug": true,
    "HibernationInfo": "                   \u0026fserver status:\n                   \u0026b\u0026lHIBERNATING",
    "Port": "25555",
    "StartingInfo": "                   \u0026fserver status:\n                    \u00266\u0026lWARMING UP",
    "TimeBeforeStoppingEmptyServer": 60
  }
}
```

current output:
```
╔═════════════════════════════════════════════╗
║  _ __ ___  ___| |__                         ║
║ | '_ ` _ \/ __| '_ \                        ║
║ | | | | | \__ \ | | |                       ║
║ |_| |_| |_|___/_| |_| v2.4.0                ║
║ Copyright (C) 2019-2021 gekigek99           ║
║ github: https://github.com/gekigek99        ║
║ remember to give a star to this repository! ║
╚═════════════════════════════════════════════╝
2022/09/02 10:38:17 targeting server address: 127.0.0.1:25566
2022/09/02 10:38:17 *** listening for new clients to connect on 0.0.0.0:25555 ...
msh start
2022/09/02 10:38:25 GetInput: user input: [msh start]
2022/09/02 10:38:25 *** MINECRAFT SERVER IS STARTING!
Error: Invalid or corrupt jarfile run.bat
2022/09/02 10:38:25 waitForExit: terminal exited
2022/09/02 10:38:25 *** MINECRAFT SERVER IS OFFLINE!
```

### Describe the solution you'd like.

a way to look at the .bat or .sh file to replace the server.jar lookups from the config file

**Comment by TheKrafter** [comment]
As `StartServer` is the entire java command, you could try replacing that with just the command to run the bash script, like 
```json
"StartServer": "sh -c serverFileName",
```

**Comment by BolverBlitz** [comment]
The .bat or .sh files are not required, forge just generates them to help people start the server.

Forge generates multiple files for args and user argst (.txt)

Simply use the new command: `"StartServerParam": "-Xms256M -Xmx1024M -Dterminal.jline=false -Dterminal.ansi=true @unix_args.txt"`
