### ISSUE TITLE
JLine Compatibility

### ISSUE THREAD

**Issue by Azarattum** [gekware/minecraft-server-hibernation#161]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

The latest version is unable to capture server logs after [JLine](https://www.curseforge.com/minecraft/mc-mods/jline-for-minecraft-dedicated-server) is initialized. The stable version `2.4.0` worked fine with it.

All versions are missing autocompletion compatibility. It would be awesome if that could be implemented somehow.

### Describe the solution you'd like.

Make `msh` support [JLine](https://www.curseforge.com/minecraft/mc-mods/jline-for-minecraft-dedicated-server) colored output. And if possible, command completion.

**Comment by gekigek99** [comment]
> The stable version 2.4.0 worked fine with it.

wdym? colored output and command completion?

on which platform? on which type of terminal? which minecraft version/flavor?

**Comment by Azarattum** [comment]
I meant server logs. After `2.4.0` while `JLine` was installed, all server logs disappeared. I wrote this issue 3 month ago, though. Haven't tested it on newer versions ever since.

Command completion has never worked on any version:
> All versions are missing autocompletion compatibility.

**Comment by gekigek99** [comment]
> After 2.4.0 while JLine was installed, all server logs disappeared (no output at all). 

this I think I can fix

> All versions are missing autocompletion compatibility.

this I think not as it's pretty rogue stuff the things that happen in terminal...
_I might add autocompletion for msh itself tho_

**Comment by gekigek99** [comment]
I added a nice terminal functionality following issue #186

also added command autocompletion for msh itself
