### ISSUE TITLE
MSH terminates lagging servers because its using the wrong check for the player count

### ISSUE THREAD

**Issue by BolverBlitz** [gekware/minecraft-server-hibernation#162]
### Current Behavior (🐛 Bug)

If a server is lagging, a joining user dosn´t update the server info.
MSH dedects the user joining but then checks the server info that returns 0 and shuts down.
![grafik](https://user-images.githubusercontent.com/35345288/193809556-81636dd5-83b6-449d-81c6-af4fc6a59092.png)

### Expected Behavior

Cache the users count within msh and either give it more time before the servr info check is performed or some other way.

### Steps to Reproduce

Have a vers slow server
Join it.
You will be in "void" because chunks are not loading.
Get kicked because msh shutdown the server.

Thats how it looks for the client connecting:
![grafik](https://user-images.githubusercontent.com/35345288/193809866-21186b43-f863-459c-aad7-228c7896871d.png)

### MSH-Version

2.4.7

### Operating system

Linux, lates MSH paper egg

### Minecraft Version

1.19.2

### Minecraft Server Software

Paper

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details.

**Comment by gekigek99** [comment]
Increasing msh server timeout time is't a viable solution?

**Comment by gekigek99** [comment]
@BolverBlitz can you check if, while the server is loading client-side, the list command is reliable?

**Comment by gekigek99** [comment]
I observed that the time passed from player joining and minecraft server player count being updated is so small that it's an edge case.

If msh users have such problems this could be related to server not being good enough to handle a minecraft server or clients having a bad connection speed.

The solution is to just set `TimeBeforeStoppingEmptyServer` to a larger value
