### ISSUE TITLE
Allow MSH to use server’s `whitelist.json`

### ISSUE THREAD

**Issue by Azarattum** [gekware/minecraft-server-hibernation#163]
Add a config option to respect server's built-in whitelist file. So, only whitelisted players can issue a server start.

Originally suggested in https://github.com/gekware/minecraft-server-hibernation/issues/124#issuecomment-1263146196

**Comment by gekigek99** [comment]
added in cf56ad73944aaaae3a01f45390e4b8e0c114d4ac

Let me know if it works for you or if you have any other problems.

_if you use msh and want to support it please give a star and consider becoming a sponsor_
