### ISSUE TITLE
Whitelist/Username string of strange characters

### ISSUE THREAD

**Issue by j4c3** [gekware/minecraft-server-hibernation#164]
### Current Behavior (🐛 Bug)

Trying to connect from a java MC client (1.19.2 - windows), the username MSH sees is string of nonsense, so, the name isn't able to be checked from the whitelist.  Below is what I see with the MSH logs set to 3. 

`2022/10/08 19:26:43 [info  ≡   ] 
�0�     *�H��                    username��+�Y�0�"0
��j~���b�V��f?�����
�Dm�9��?���N;
             �F�@�j�i��
                       6��)
                           l$ji��������U&.د���xzL6pC��qF�?��J�~-:l��D&"�V8�j��Qp�����dK$���s��ӆ?>1��3��N���$��U[��Ye�a�#��*脊ut��܈��{4��%~���MҀ���J�J̽z�ns(removed a backtick here for github)��({��
                                                                                                                                                                @X����V��
                                                                                                                                                                         jZ��E��贚I9H]���nrO��K�e�?yL=s���ԧ���$C/�d�h
�pї���h^n���<�c��K����RŮ���E��R.�q^ �����?�T.%��:�s��'���\���z�{-x�LNUC%�"�(
                                                                            l�|��kB�z{��P3թ�WrFg�v�Oe⎹~�E�
                                                                                                          Fz������1��@Vq|�J3�   i�#ݵ�~��Lҹ����~b ���� 
�[��ȏ���s�Q��*�4P�??bp�'�j7ȿ8s��|���������c�B�qn����� ��f)fY&J$��;����N�a��{S���I'��TW�����~���
��5�~�〧9!(������G�K��Ժ>޺��oGCW���n���X��2�|26  x�� 8$                                         �HBH���Ѡ�r���@�Ԋ[�~] �?n`K+[�`���?
                                                      wВ����F��ֽr�����Et�N�C�?-/��m��w4�C�,)�p��IF��xR�0P�f����י5� uMΣ��@7�+ tried to join from 192.168.1.225:25555 to 127.0.0.1:25565
`

### Expected Behavior

Just the username being checked against the whitelist.

### Steps to Reproduce

The username in question is just a string of all lowercase characters, nothing extra.

### MSH-Version

2.4.7

### Operating system

Docker

### Minecraft Version

1.19.2

### Minecraft Server Software

Paper

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details.

**Comment by gekigek99** [comment]
bugfix implemented in commit https://github.com/gekware/minecraft-server-hibernation/commit/5ac97113133ce6e9237008eb8250b937aa1d2d79

Let me know if it works for you or if you have any other problems.

_if you use msh and want to support it please give a star and consider becoming a sponsor_
