### ISSUE TITLE
set the minecraft server's port

### ISSUE THREAD

**Issue by Vosjedev** [gekware/minecraft-server-hibernation#167]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

when looking at the config files, i cant find an option to set the minecraft server's port.
i would like to configure the listener to listen to port 25565, and redirect to 25555.
if this option is there, and just did not see it, please give me the filename and line nr.

### Describe the solution you'd like.

an option in config to set the redirect port

**Comment by gekigek99** [comment]
If you like msh give a star and consider supporting the project!
