### ISSUE TITLE
MSH not finding my server.jar

### ISSUE THREAD

**Issue by Vosjedev** [gekware/minecraft-server-hibernation#168]
### Current Behavior (🐛 Bug)

I just installed MSH, and configured it. I made sure to type all paths correctly, and checked 3 times. And then I ran it for the first time. Then, it says
`[error ***  ] main: LoadConfig: checkConfigRuntime: specified server file/folder does not exist: {/home/user/server/smp2}/{spigot-1.19.2.jar}` and exits with status 1.
why is this? 

### Expected Behavior

MSH just starting.

### Steps to Reproduce

Install a spigot server, cd to the server's folder, run the build steps in the readme, run `./msh.`

### MSH Logs

I need to retype the logs as my server is on a linux CLI, so I am skipping the title.

```
[ info *   ] checking OS support...
[ info *   ] loading config default...
[ info *   ] loading loading config runtime...
[error ***  ] main: LoadConfig: checkConfigRuntime: specified server file/folder does not exist: {/home/user/server/smp2}/{spigot-1.19.2.jar}
```

### MSH-Version

2.4.4

### Operating system

Fedora server 36

### Minecraft Version

1.19.2

### Minecraft Server Software

spigot

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details.

**Comment by Vosjedev** [comment]
I now see that the log's code block skipped my newlines... oops!

**Comment by gekigek99** [comment]
you should remove all the parenthesis: `{ }`

**Comment by Vosjedev** [comment]
i tried, now the error has changed:
```[ error ***  ] main: LoadConfig: checkConfigRuntime: specified server file/folder does not exist:```
and then nothing...

**Comment by gekigek99** [comment]
Can you send the msh-config.json?

**Comment by Vosjedev** [comment]
here is is:
```
{
  "Server": {
    "Folder": "/home/user/server/smp2",
    "FileName": "spigot-1.19.2.jar",
    "Protocol": 756,
    "Version": "1.19.2"
  },
  "Commands": {
    "StartServer": "java <Commands.StartServerParam> -jar <Server.FileName> nogui",
    "StartServerParam": "-Xms2g -Xmx2g",
    "StopServer": "stop",
    "StopServerAllowKill": 0
  },
  "Msh": {
    "Debug": 1,
    "InfoHibernation": "                   §fserver status:\n                   §b§lHIBERNATING",
    "InfoStarting": "                   §fserver status:\n                    §6§lWARMING UP",
    "NotifyUpdate": true,
    "ListenPort": 25565,
    "TimeBeforeStoppingEmptyServer": 30
  }
}

```

**Comment by gekigek99** [comment]
can you check with the latest version?
compile from dev branch

**Comment by Vosjedev** [comment]
does git autoupdate the files? i launched msh and it worked, did not do anything at all...

**Comment by gekigek99** [comment]
I don't think so, try `git pull` in msh rep folder and see if it does anything.

But if it works we are good!

_if you use msh and want to support it please give a star and consider becoming a sponsor_

**Comment by Vosjedev** [comment]
it came back, the problem occures when editing the config. a restart fixes it, until i edit the config again. trying ` git pull ` this weekend. if that does not update, i will look into git's man page. thanks!

**Comment by Vosjedev** [comment]
a restart of my computer.

**Comment by gekigek99** [comment]
> until i edit the config again

what edit do you perform on the config?

anyway try again with a recent version, but i think its not a problem of msh

**Comment by Vosjedev** [comment]
I came to that conclusion too. I hope updating still fixes it. I guess I am not going to edit the config in a long time, and when I do, I am restarting my computer anyways to restart the whole server program list running. Thanks for looking into the issue!
