### ISSUE TITLE
Doesn't start

### ISSUE THREAD

**Issue by Chris6ix** [gekware/minecraft-server-hibernation#176]
### Current Behavior (🐛 Bug)

I downloaded `msh-v2.4.10-d93e0a3-windows-386.exe` and double-clicked it.
There was a pop-up from the Windows Security that it doesn't trust it, but I allowed it to run, then the command prompt showed up for a split second and went away again.
Nothing else happened.

### Expected Behavior

The program starts and sets up a config file

### Steps to Reproduce

/\

### MSH Logs

/

### MSH-Version

2.4.10

### Operating system

Windows 10

### Minecraft Version

1.19.3

### Minecraft Server Software

Paper

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details.

**Comment by Chris6ix** [comment]
I managed to fix the issue by placing the downloadable config next to it...I thought msh would generate a config on its own...

**Comment by gekigek99** [comment]
Yeah its always best to launch it from cmd/powershell instead of double click it.

You would have seen the problem immediately.
