### ISSUE TITLE
msh query protocol support (used by home assistant)

### ISSUE THREAD

**Issue by codahq** [gekware/minecraft-server-hibernation#177]
Services like Home Assistant (and better game server monitoring sites and tools) don't report anything correctly when the MC server is stopped.  Would it be possible to capture things like server message, protocol, version, max player count when the server is online and return it with current player count 0 to whatever protocol and port is used to query servers?  

This way the server still appears to be online to Home Assistant and other services when it is asleep because it is reachable after it warms up.

**Comment by gekigek99** [comment]
msh is already doing so.

When ms is frozen, msh emulates a server info response whenever a client refreshes its server page. (showing 0 players, version, ping, and the specified frozen MOTD)

**Comment by codahq** [comment]
In which version?  The latest release version returns no information and Home Assistant's monitoring implementation sets it to offline while it is hibernating.

**Comment by gekigek99** [comment]
What do you mean "sets it offline"?

Is the assistant configured correctly, with right msh address/port?

How is the assistant retrieving the ms informations?

**Comment by codahq** [comment]
https://github.com/py-mine/mcstatus/blob/master/mcstatus/server.py

It looks like Home Assistant uses query protocol?  Does the Minecraft game client use a different protocol to get server information?

**Comment by gekigek99** [comment]
msh is using main minecraft server TCP port to perform status response and is capable of emulating it when minecraft server is offline (https://wiki.vg/Protocol#Status)

Home Assistant is using query protocol instead, which msh does not implement.

----

maybe you can set the Home Assistant to perform requests as status  request on main minecraft server TCP port?

**Comment by gekigek99** [comment]
added a test query handler here: 49a1ff3a8fb0484d6c67e4f0deca1790c990498e

**Comment by codahq** [comment]
thank you for the reply and looking at this more with me.  yes, i could do a PR to the home assistant team and ask them to update the method in which they poll the minecraft server to use TCP status instead of query.  i don't think a PR like that would be approved unfortunately.  they would even reference maybe your [link](https://wiki.vg/Query) to suggest that query protocol is the appropriate method.  

that is why i came to your project.  i am grateful that you have already even added a test handler.  do you think that you will continue to add query support?

**Comment by gekigek99** [comment]
> could do a PR to the home assistant team and ask them to update the method in which they poll the minecraft server to use TCP status instead of query. i don't think a PR like that would be approved unfortunately. they would even reference maybe your [link](https://wiki.vg/Query) to suggest that query protocol is the appropriate method.

well I think that the 2 methods are different and independent, if you look at server.properties you can enable/disable them independently. It would for sure make the home assistant service more complete especially because the query method is disabled by default on vanilla servers and only the status method is enabled.

> that is why i came to your project. i am grateful that you have already even added a test handler. do you think that you will continue to add query support?

Well I opened a branch cause I think it's pretty doable, especially with the great documentation online. It feels good to be back adding stuff and not only removing code and bugs XD

**Comment by gekigek99** [comment]
@codahq can you compile query branch and test if the test query handler is working?

just set query.port in server.properties to be the same of the minecraft server, launch msh and check if the home assistant can see a response

**Comment by codahq** [comment]
i don't have a development environment for go but i can set one up if you don't have a binary for me to download.

**Comment by gekigek99** [comment]
you can download [msh-v2.4.10-1fc94c0.zip](https://github.com/gekware/minecraft-server-hibernation/files/10329528/msh-v2.4.10-1fc94c0.zip)

If you need an other arch tell me

**Comment by gekigek99** [comment]
functionality was added at 1b2c2fea988e686ab36675da14bd0d96f88595e9

@codahq would you mind doing some bughunt?

**Comment by gekigek99** [comment]
made the [v2.4.11 release](https://github.com/gekware/minecraft-server-hibernation/releases/tag/v2.4.11)
