### ISSUE TITLE
Console Colors not working

### ISSUE THREAD

**Issue by Chris6ix** [gekware/minecraft-server-hibernation#178]
### Current Behavior (🐛 Bug)

Currently, only the colors coming from msh are working, everything that comes from the minecraft server is gray.

### Expected Behavior

All colors work.

### Steps to Reproduce

Start the server?

### MSH Logs

Example of msh logs:
![image](https://user-images.githubusercontent.com/65610536/208938752-7de080f4-15bb-47c5-bb8a-8986d140c04e.png)
Example of Minecraft Server logs:
![image](https://user-images.githubusercontent.com/65610536/208939089-3ea6fb0e-2cfc-47b2-871a-80663c5d8066.png)

### MSH-Version

2.4.10

### Operating system

Windows 10

### Minecraft Version

1.19.3

### Minecraft Server Software

Paper

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details.

**Comment by gekigek99** [comment]
Where do you see minecraft server log colors?

**Comment by Chris6ix** [comment]
> Where do you see minecraft server log colors?

Before I started to use msh I saw the colors trough cmd

**Comment by gekigek99** [comment]
apparently it's not possible as the ms terminal can't interpret escape codes for color and style.

I tried many ways and it seems to be impossible to fix it as ms is running in a very peculiar terminal.

**Comment by Chris6ix** [comment]
That's very unfortunate...and it's not possible to use the default cmd for msh?

**Comment by gekigek99** [comment]
the problem is that msh is enabling colors for its own terminal (thats why msh logs are colored) but cannot enable colors on the "hidden" ms terminal

**Comment by Chris6ix** [comment]
Alright

**Comment by Geniucker** [comment]
But in this way I can get messy log like
```
2023/09/08 16:19:57.158 [serv  ≡≡  ] [39;0m[[32;22m16:19:57[39;0m] [[32;22mServer thread/INFO[39;0m] [[32;22mMinecraft[39;0m]: [32;22mPumpkin Growth Modifier: 100%!(NOVERB)
2023/09/08 16:19:57.158 [serv  ≡≡  ] [39;0m[[32;22m16:19:57[39;0m] [[32;22mServer thread/INFO[39;0m] [[32;22mMinecraft[39;0m]: [32;22mSapling Growth Modifier: 100%!(NOVERB)
2023/09/08 16:19:57.158 [serv  ≡≡  ] [39;0m[[32;22m16:19:57[39;0m] [[32;22mServer thread/INFO[39;0m] [[32;22mMinecraft[39;0m]: [32;22mWheat Growth Modifier: 100%!(NOVERB)
2023/09/08 16:19:57.158 [serv  ≡≡  ] [39;0m[[32;22m16:19:57[39;0m] [[32;22mServer thread/INFO[39;0m] [[32;22mMinecraft[39;0m]: [32;22mNetherWart Growth Modifier: 100%!(NOVERB)
2023/09/08 16:19:57.158 [serv  ≡≡  ] [39;0m[[32;22m16:19:57[39;0m] [[32;22mServer thread/INFO[39;0m] [[32;22mMinecraft[39;0m]: [32;22mVine Growth Modifier: 100%!(NOVERB)
2023/09/08 16:19:57.158 [serv  ≡≡  ] [39;0m[[32;22m16:19:57[39;0m] [[32;22mServer thread/INFO[39;0m] [[32;22mMinecraft[39;0m]: [32;22mCocoa Growth Modifier: 100%!(NOVERB)
2023/09/08 16:19:57.158 [serv  ≡≡  ] [39;0m[[32;22m16:19:57[39;0m] [[32;22mServer thread/INFO[39;0m] [[32;22mMinecraft[39;0m]: [32;22mEntity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
2023/09/08 16:19:57.158 [serv  ≡≡  ] [39;0m[[32;22m16:19:57[39;0m] [[32;22mServer thread/INFO[39;0m] [[32;22mMinecraft[39;0m]: [32;22mHopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
2023/09/08 16:19:57.159 [serv  ≡≡  ] [39;0m[[32;22m16:19:57[39;0m] [[32;22mServer thread/INFO[39;0m] [[32;22mMinecraft[39;0m]: [32;22mRandom Lighting Updates: false
2023/09/08 16:19:57.159 [serv  ≡≡  ] [39;0m[[32;22m16:19:57[39;0m] [[32;22mServer thread/INFO[39;0m] [[32;22mMinecraft[39;0m]: [32;22mStructure Info Saving: true
```
Maybe characters concerning color can be removed
