### ISSUE TITLE
Discord Server invite invalid

### ISSUE THREAD

**Issue by Chris6ix** [gekware/minecraft-server-hibernation#179]
### Current Behavior (🐛 Bug)

I wanted to join the Discord server to ask a few questions, but the discord invite (https://discord.com/invite/mBSnEypcYC) returns this:
![image](https://user-images.githubusercontent.com/65610536/208940193-891c91e0-2fbf-44ac-82d3-28b62fb9f6b3.png)

### Expected Behavior

Invite works

### Steps to Reproduce

Use https://discord.com/invite/mBSnEypcYC

### MSH Logs

/

### MSH-Version

/

### Operating system

/

### Minecraft Version

/

### Minecraft Server Software

/

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details.

**Comment by gekigek99** [comment]
thanks for reporting!

new link set to https://discord.gg/guKB6ETeMF
