### ISSUE TITLE
`TimeBeforeStoppingEmptyServer` not working when no imput in console

### ISSUE THREAD

**Issue by Chris6ix** [gekware/minecraft-server-hibernation#180]
### Current Behavior (🐛 Bug)

The `TimeBeforeStoppingEmptyServer` doesn't work when there is nothing happening on the console.
I set it to 900s (15 minutes) and just waited without a player being on the server to see if the automatic shutdown works as I expect.
After I waited for 25 minutes without the server being shut down, I wanted to see if the program was stuck or something, so I just wanted to type "test" into the console, but as soon as I typed "t" msh finally checked if there were players online and because there were none, it shut down the server.

### Expected Behavior

Shut down the server when there haven't been players on for 15 minutes.

### Steps to Reproduce

Set up a `TimeBeforeStoppingEmptyServer` of `900s`
Start msh
Wait without having any imput to the console
See that even after the 15 minutes passed, msh does not shut down the server.

### MSH Logs

![image](https://user-images.githubusercontent.com/65610536/208945392-7a22e3c1-0c9b-476f-b308-3278b4d53544.png)

### MSH-Version

2.4.10

### Operating system

Windows 10

### Minecraft Version

1.19.3

### Minecraft Server Software

Paper

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details.

**Comment by gekigek99** [comment]
does it also happen when setting to 60 s?

Currently I can't reproduce the bug, does it happen everytime to you?

**Comment by Chris6ix** [comment]
> does it also happen when setting to 60 s?
> 
> Currently I can't reproduce the bug, does it happen everytime to you?

I will check that tomorrow and get back to you

**Comment by Chris6ix** [comment]
I have tried again now with `60s`, `120s` and `900s` and that problem didn't occur again...so I can't even reproduce it myself now...
I don't know why it did that yesterday then...
Here is it working fine with `900s`:
![image](https://user-images.githubusercontent.com/65610536/209173144-40525004-db9b-4a31-9412-095fa92e7bfa.png)
I am closing this issue then and if it happens again in the future, I'm going to open a new one.
