### ISSUE TITLE
MSH error when trying to get player count

### ISSUE THREAD

**Issue by Chris6ix** [gekware/minecraft-server-hibernation#181]
### Current Behavior (🐛 Bug)

Msh errors when trying to get player count

### Expected Behavior

Msh gets player count without error

### Steps to Reproduce

Start msh
Start server
wait for msh to check for player count

### MSH Logs

![image](https://user-images.githubusercontent.com/65610536/208946741-e194d172-8747-4632-99de-8e2e3b8329b6.png)

### MSH-Version

2.4.10

### Operating system

Windows 10

### Minecraft Version

1.19.3

### Minecraft Server Software

Paper

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details.

**Comment by gekigek99** [comment]
The first error in the log happens everytime playercount is checked? _(it happears a connection error not correlated to msh, especially if msh proxy normally works)_

I opened #183 for the second error in the log

**Comment by Chris6ix** [comment]
> The first error in the log happens everytime playercount is checked? _(it happears a connection error not correlated to msh, especially if msh proxy normally works)_

Yeah, the first error seems to always be there when playercount is checked, but I have no idea what it means.

**Comment by gekigek99** [comment]
but you can connect to 127.0.0.1:25565 with a minecraft client no?

**Comment by Chris6ix** [comment]
From my main PC? No.
I get this:
![2022-12-22_21 14 31](https://user-images.githubusercontent.com/65610536/209218606-01fd30ef-1dc2-496e-9c57-97eceeccbe34.png)
I always use the private ip address of my Server PC to connect to my MC server.

**Comment by gekigek99** [comment]
yeah with that you can connect? 

x.x.x.x:25565 (the port of the ms not of msh)

**Comment by Chris6ix** [comment]
Yes.
With the private ip I can connect to both msh and the ms.

**Comment by gekigek99** [comment]
mmmmm weird...

anyway, that's why for playercount there are 3 methods.

**Comment by gekigek99** [comment]
if you want you can set loglevel to 4 and generate again the error... maybe I can discover something from bytes echanged

**Comment by Chris6ix** [comment]
> if you want you can set loglevel to 4 and generate again the error... maybe I can discover something from bytes echanged

I tried again with log level 4, but there is no difference at that part...
The error still looks like this.
![image](https://user-images.githubusercontent.com/65610536/209475931-33d5b3c9-bd9c-4d6e-a5f5-0497709a4c8b.png)

**Comment by gekigek99** [comment]
that's weird cause it means that msh cannot connect to the minecraft server locally.

But then when a player joins through msh it's connection is forwarded to the minecraft server locally, and everything works.

**Comment by Chris6ix** [comment]
> that's weird cause it means that msh cannot connect to the minecraft server locally.
> 
> But then when a player joins through msh it's connection is forwarded to the minecraft server locally, and everything works.

Well, I also get this error when a player joins the server...
![image](https://user-images.githubusercontent.com/65610536/209483027-a3e424c1-0dfc-48a6-9929-f1f234f80aaf.png)
But the connection works...so everyone can join and play on my server just like before...so this error is kind of "fake" (If this error wouldn't show, then I would not think anything is wrong).

**Comment by gekigek99** [comment]
can you share a full log (not pic) of a client joining where this error is shown?

**Comment by Chris6ix** [comment]
> can you share a full log (not pic) of a client joining where this error is shown?
> 
> (with loglevel set to 4)

2022/12/26 02:33:32 [byte      ] client --> msh: [21 0 249 5 14 49 57 50 46 49 54 56 46 49 55 56 46 51 53 99 211 1]
2022/12/26 02:33:32 [info  ≡   ] a client requested server info from 192.168.178.66:25555 to 127.0.0.1:25565
2022/12/26 02:33:34 [error ≡   ] openProxy: dial tcp 127.0.0.1:25565: connectex: No connection could be made because the target machine actively refused it. [02f200]
2022/12/26 02:33:34 [byte      ] msh --> client: [236 0 0 233 0 123 34 116 101 120 116 34 58 34 99 97 110 39 116 32 99 111 110 110 101 99 116 32 116 111 32 115 101 114 118 101 114 46 46 46 32 99 104 101 99 107 32 105 102 32 109 105 110 101 99 114 97 102 116 32 115 101 114 118 101 114 32 105 115 32 114 117 110 110 105 110 103 32 97 110 100 32 115 101 116 32 116 104 101 32 99 111 114 114 101 99 116 32 116 97 114 103 101 116 80 111 114 116 34 125]
2022/12/26 02:33:34 [serv  ≡≡  ] [02:33:34 INFO]: UUID of player Chris6ix is b09b0661-ea58-4934-ba16-0b6e08c5920c
2022/12/26 02:33:35 [serv  ≡≡  ] [02:33:35 INFO]: Chris6ix[/192.168.178.66:62583] logged in with entity id 141 at ([SV_the_end]1065.6266635066415, 105.0, 4506.20737902927)
2022/12/26 02:33:35 [serv  ≡≡  ] [02:33:35 INFO]: Welcome, [Owner] Chris6ix!

**Comment by gekigek99** [comment]
> ```
>2022/12/26 02:33:34 [byte      ] msh --> client: [236 0 0 233 0 123 34 116 101 120 116 34 58 34 99 97 110 39 116 32 99 111 110 110 101 99 116 32 116 111 32 115 101 114 118 101 114 46 46 46 32 99 104 101 99 107 32 105 102 32 109 105 110 101 99 114 97 102 116 32 115 101 114 118 101 114 32 105 115 32 114 117 110 110 105 110 103 32 97 110 100 32 115 101 116 32 116 104 101 32 99 111 114 114 101 99 116 32 116 97 114 103 101 116 80 111 114 116 34 125]
> ```

here msh is reporting to the client (message will be shown in connection screen): 
```
[236][0][0][233][0]{"text":"can't connect to server... check if minecraft server is running and set the correct targetPort"}
```

do you have some weird port redirection/firewall ecc... cause it really weird... you should not even be able to enter ms world.

the ms is running on `127.0.0.1:25565` no?

does msh start and stop correctly the server?

**Comment by Chris6ix** [comment]
> the ms is running on `127.0.0.1:25565` no?

Oh...that was the problem...it was not. It was running on `192.168.178.35:25565` (The private IP of my server)
I just checked with `127.0.0.1` and the error on join is gone.
And with 127.0.0.1 I can start the server and join with the same Server Profile (`192.168.178.35:25555`)
Before I had one server profile to start the server with `192.168.178.35:25555` and one to join the server `192.168.178.35:25565`
I had configured it wrongly then...but the [Instructions](https://github.com/gekware/minecraft-server-hibernation#instructions) didn't say anything about `127.0.0.1`...so I just configured it how I ran the server before without msh.
It would be good if that would be explained then for future people that want to use msh.

There is just one thing left then...I just saw that now when it's configured correctly, the console gets spammed with this when a player is on the ms server, which is really annoying and clutters up the console a lot.
If this is important for you (or other people), then please add a config option to enable/disable this (Something like `ShowDataTransfer` maybe?)
![image](https://user-images.githubusercontent.com/65610536/209566072-e5a882c3-7114-402b-b668-9f44e01dd2ae.png)

Thank you for helping me :)

> does msh start and stop correctly the server?

Yes, it did start and stop the server correctly.

**Comment by gekigek99** [comment]
> It would be good if that would be explained then for future people that want to use msh.

yeah sure I can add it to the instructions, I just need you to specify a bit more your setup cause I didn't grasp really well... (@BolverBlitz)

> I just checked with 127.0.0.1 and the error on join is gone.

what do you mean you checked?

> the [Instructions](https://github.com/gekware/minecraft-server-hibernation#instructions) didn't say anything about 127.0.0.1

yeah I assumed that the minecraft server runs on the same machiene of msh and that msh can reach it through `127.0.0.1`

> There is just one thing left then...I just saw that now when it's configured correctly, the console gets spammed with this when a player is on the ms server, which is really annoying and clutters up the console a lot.

If you want to keep server logs you can set loglevel to 2 instead of 3 which is actually for developement, but yeah I'll consider adding a variable.

**Comment by BolverBlitz** [comment]
Well, by default minecraft awaits connections on 0.0.0.0 and i think what the issue here was he wrote `server-ip=192.168.178.35` correct?

Default 0.0.0.0 would work in both cases, while the other dosn´t work because msh dosn´t connect via the privat ip. Its just local.
This could be added to documentation, but only as a side node because default it works and there isn´t a big reason to ever modify that. Usualy you do it when there is multihome involved.

**Comment by Chris6ix** [comment]
> > It would be good if that would be explained then for future people that want to use msh.
> 
> yeah sure I can add it to the instructions, I just need you to specify a bit more your setup cause I didn't grasp really well... (@BolverBlitz)

Well, I had my ms running on `192.168.178.35:25565` because that is what I used before I started using msh.
Then I installed msh on the same system and configured it to listen to `192.168.178.35:25555`.
Then I used a 2nd server profile in the Minecraft client connects to `192.168.178.35:25555` to connect to msh and start the server.
When the server was started, I used my 1st server profile, that I always used to join the ms with `192.168.178.35:25565`.

I did this because I didn't know that the ms should be configured to run on `127.0.0.1` to nicely work with msh.
> > I just checked with 127.0.0.1 and the error on join is gone.
> 
> what do you mean you checked?

I set my ms to 127.0.0.1, then started it trough msh and joined the ms...
> > the [Instructions](https://github.com/gekware/minecraft-server-hibernation#instructions) didn't say anything about 127.0.0.1
> 
> yeah I assumed that the minecraft server runs on the same machiene of msh and that msh can reach it through `127.0.0.1`

It is on the same system, but the ms was not running on `127.0.0.1`, so msh was not able to reach it there.
> > There is just one thing left then...I just saw that now when it's configured correctly, the console gets spammed with this when a player is on the ms server, which is really annoying and clutters up the console a lot.
> 
> If you want to keep server logs you can set loglevel to 2 instead of 3 which is actually for developement, but yeah I'll consider adding a variable.

Sure

**Comment by Chris6ix** [comment]
> Well, by default minecraft awaits connections on 0.0.0.0 and i think what the issue here was he wrote `server-ip=192.168.178.35` (in server.properties) correct?

Yes, I had `server-ip=192.168.178.35` in server.properties, because that is how I used the ms for over 2 years before and that always worked perfectly before msh.
> Default 0.0.0.0 would work in both cases, while the other dosn´t work because msh dosn´t connect via the privat ip. Its just local. This could be added to documentation, but only as a side node because default it works and there isn´t a big reason to ever modify that. Usualy you do it when there is multihome involved.

Yeah, a better documentation would be nice. I think I would have found the mistake earlier if it was explained better.

**Comment by gekigek99** [comment]
I added a reminder here: 18f0234e6120c84ba800b5ff1fc75eaa821bc5b8

**Comment by gekigek99** [comment]
> Well, I had my ms running on 192.168.178.35:25565 because that is what I used before I started using msh.
Then I installed msh on the same system and configured it to listen to 192.168.178.35:25555.
Then I used a 2nd server profile in the Minecraft client connects to 192.168.178.35:25555 to connect to msh and start the server.
When the server was started, I used my 1st server profile, that I always used to join the ms with 192.168.178.35:25565.

Shower tought: you know that you don't need this trickery to use msh right? 

you should have the ms on 25565 and msh listening to 25555. Then with one minecraft client you can connect to `192.168.178.35:25555` to start the server and (a few seconds later) to join it/play.

**Comment by Chris6ix** [comment]
> Shower tought: you know that you don't need this trickery to use msh right?

I know that now. Before you asked if my server was running on `127.0.0.1`, which made me see my mistake, I thought "this trickery" was how you're supposed to use msh.
> you should have the ms on 25565 and msh listening to 25555. Then with one minecraft client you can connect to `192.168.178.35:25555` to start the server and (a few seconds later) to join it/play.

I now have my ms set to `127.0.0.1:25555` and msh to `25565` because I don't want to put `:25555` behind my DNS to keep it clean. Only I use `192.168.178.35` to connect to the server, while my friends use my DNS.
It was all because I didn't know that msh couldn't connect to the ms if it wasn't on `127.0.0.1`, because that wasn't explained in the documentation. But now everything is working perfectly :)
