### ISSUE TITLE
Server icon bugged

### ISSUE THREAD

**Issue by Chris6ix** [gekware/minecraft-server-hibernation#182]
### Current Behavior (🐛 Bug)

At first, the minecraft server icon was fine and msh had the snowy dirt block as an icon, but now msh has replaced the minecraft server icon with a sun and the msh icon with 4 small images of the moon next to the snowy dirt block

![2022-12-21_17 00 15](https://user-images.githubusercontent.com/65610536/208950433-8f025765-707c-4fe8-9afd-37695c612e46.png)

### Expected Behavior

Not change the icon of the mc server and display the snowy dirt block for msh.

### Steps to Reproduce

Start msh and start server?

### MSH Logs

Not sure if it is related as it also happened before this log, but now it's getting warnings and errors when I spam refresh from my minecraft client:
![image](https://user-images.githubusercontent.com/65610536/208950277-25606b1a-52e6-416d-89f8-6edd6cf834a4.png)

### MSH-Version

2.4.10

### Operating system

Windows 10

### Minecraft Version

1.19.3

### Minecraft Server Software

Paper

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details.

**Comment by gekigek99** [comment]
I am aware of this bug.

But I didn't find any msh related cause and think its just caused by a graphical error on client side.

**Comment by Chris6ix** [comment]
> I am aware of this bug.
> 
> But I didn't find any msh related cause and think its just caused by a graphical error on client side.
> 
> If you have any idea/suggestion on how to solve it I would gladly listen to it.

I'm not a programmer, so I can't tell you exactly how to fix that, but my suggestion would be to just stop msh from modifying icons overall.
I don't really see the benefit in that, so I would just make msh display the snowy dirt block all the time and leave the mc server's be.

**Comment by gekigek99** [comment]
but msh is not modifying anything if you don't add a personalized image. msh uses the default pic without modifying it.

If you restart minecraft client it might actually be fixed.

**Comment by Chris6ix** [comment]
Hmm...that's weird...how does this issue happen then if it "uses the default pic without modifying it"?
Because I have never seen that before i started using msh...

**Comment by gekigek99** [comment]
yeah Idk
months ago I tested it looking at the bytes exchanged and coudnt find a correlation.

Proabably it has to do with msh sending a "static" image not adapted to the situation and the client to save bandwidth stores it wrong until it decides to reload it.

**Comment by Chris6ix** [comment]
Oh, alright
I'm closing this issue then, so you can pin it.
That way people that have that bug know it's already known and can't really be fixed.
