### ISSUE TITLE
MSH spamming warnings when plugin pastes stacktrace

### ISSUE THREAD

**Issue by Chris6ix** [gekware/minecraft-server-hibernation#184]
### Current Behavior (🐛 Bug)

Msh spams `[warn  ≡≡  ] func1: line does not adhere to expected log format [00f203]` between every line of a stacktrace, making it very hard and annoying to read the error.

### Expected Behavior

No warning, so that I can properly read the plugin's error

### Steps to Reproduce

Get a plugin error in console (By for example misconfiguring a plugin)

### MSH Logs

![image](https://user-images.githubusercontent.com/65610536/209022921-0d3f55cf-d270-4f82-84be-a439d4962e6d.png)

### MSH-Version

2.4.10

### Operating system

Windows 10

### Minecraft Version

1.19.3

### Minecraft Server Software

Paper

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details.

**Comment by gekigek99** [comment]
would you mind sharing the text log with the image next time? really makes the work faster lol

**Comment by Chris6ix** [comment]
> would you mind sharing the text log with the image next time? really makes the work faster lol

Sure

> fixed in [09165c8](https://github.com/gekware/minecraft-server-hibernation/commit/09165c8df172de8a96681c61f3a463b908e8fff7)

Thanks!
