### ISSUE TITLE
Remove `a chat message was sent` info

### ISSUE THREAD

**Issue by Chris6ix** [gekware/minecraft-server-hibernation#185]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

It would be great if you could disable that msh sends `a chat message was sent` info, as it doesn't have a use and in my opinion just unnecessarily clutters up the console.

![image](https://user-images.githubusercontent.com/65610536/209034417-7a3ef751-2df6-41e7-81f1-f654ea830324.png)
![image](https://user-images.githubusercontent.com/65610536/209034472-fd751c67-ca4d-4191-8231-73107d2aa303.png)

### Describe the solution you'd like.

Either completely remove the `a chat message was sent` info from msh or add a setting into the config that when set to `false` disables it.
A name for that setting could be `ChatMessageInfo` or something similar.

### Additional context to this request.

/

**Comment by gekigek99** [comment]
fixed in ddc5ea202743697fecabd8f24e68254fa5778de8

**Comment by Chris6ix** [comment]
> fixed in [ddc5ea2](https://github.com/gekware/minecraft-server-hibernation/commit/ddc5ea202743697fecabd8f24e68254fa5778de8)

Thank you very much!
