### ISSUE TITLE
Typing in console gets interrupted when something happens in console

### ISSUE THREAD

**Issue by Chris6ix** [gekware/minecraft-server-hibernation#186]
### Current Behavior (🐛 Bug)

When you are currently typing something into the console such as `mine give Chris6ix diamond` and while you type something happens in the console such as a player using a command or msh receiving a connection, the text you type gets cut off and put at the beginning of that line.
This causes you to have to type the command all over again.
This behavior does not happen on a normal MC server running through cmd without msh.

### Expected Behavior

Msh doesn't cut you off just like the default cmd does.

### Steps to Reproduce

Type something into the console (Such as `mine give PLAYER_NAME diamond`) and make some other player use a command while you type into the console.
See that your text gets cut off.

### MSH Logs

/

### MSH-Version

2.4.10

### Operating system

Windows 10

### Minecraft Version

1.19.3

### Minecraft Server Software

Paper

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details.

**Comment by gekigek99** [comment]
> This causes you to have to type the command all over again.

not really, if you finisch typing your command and press enter the input is correct.

so it's not vital as server terminal it's not something you interact with every day (especially if using msh that automatize the start and stop of the server) but I agree it's not super nice as user experience.

**Comment by Chris6ix** [comment]
> > This causes you to have to type the command all over again.
> 
> not really, if you finisch typing your command and press enter the input is correct.

Well, yeah...if you finish it. But the problem is that you can't finish it.

> so it's not vital as server terminal it's not something you interact with every day (especially if using msh that automatize the start and stop of the server) but I agree it's not super nice as user experience.

For me, it is quite important, as I (or my dev) can update/fix smaller things like that without having to join the server.
I reload plugins I work on quite often from the console.

**Comment by gekigek99** [comment]
added in f1d6781325eef2f957df9494844522fe2bcdb0a2

**Comment by Chris6ix** [comment]
> added in [f1d6781](https://github.com/gekware/minecraft-server-hibernation/commit/f1d6781325eef2f957df9494844522fe2bcdb0a2)

Thank you very much :)
