### ISSUE TITLE
Warning on start

### ISSUE THREAD

**Issue by Chris6ix** [gekware/minecraft-server-hibernation#187]
### Current Behavior (🐛 Bug)

It's not super important and seems to not cause problems, but I just wanted to report that I get this warning on every msh startup:

`[warn  ≡   ] sgmMgr: response status code is 400 Bad Request -> prolonging segment... [01f000]`

![image](https://user-images.githubusercontent.com/65610536/209476547-10f94d74-fedb-4748-b67c-a249bf9f61dc.png)

### Expected Behavior

No warning i guess

### Steps to Reproduce

Start msh?

### MSH Logs

![image](https://user-images.githubusercontent.com/65610536/209476669-5339ce1b-43b1-4229-b0ab-80c630bc3699.png)

### MSH-Version

2.4.10

### Operating system

Windows 10

### Minecraft Version

1.19.3

### Minecraft Server Software

Paper

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details.

**Comment by gekigek99** [comment]
thanks for reporting but it was already fixed in 5173f6cbdbc90853f7e6b291a80f84193d048a27

If you compile the latest dev commit the error should not be present

**Comment by Chris6ix** [comment]
> thanks for reporting but it was already fixed in [5173f6c](https://github.com/gekware/minecraft-server-hibernation/commit/5173f6cbdbc90853f7e6b291a80f84193d048a27)
> 
> If you compile the latest dev commit the error should not be present

Nice!

When are you going to release version 2.5?
Because I am sadly unable to build msh myself.

**Comment by gekigek99** [comment]
if you tell me which os/arch I can build it for you

**Comment by Chris6ix** [comment]
> if you tell me which os/arch I can build it for you

Windows 10...it's in all of my bug reports.

**Comment by gekigek99** [comment]
ah yeah I always forget that @BolverBlitz built a fastastic issue layout.

Here you go: [msh.zip](https://github.com/gekware/minecraft-server-hibernation/files/10303204/msh.zip)

**Comment by Chris6ix** [comment]
Thank you :)

**Comment by Chris6ix** [comment]
I just unzipped it and there are 2 .exe files...`msh-v2.4.10-325269a-windows-amd64.exe` and `msh-v2.4.10-325269a-windows-386.exe`.
I was using the `386` before...is that still the correct one?

**Comment by gekigek99** [comment]
if you have a 64bit system then its better to use the amd64 otherwise you can use the 386.

They are the same, just 2 architectures

**Comment by Chris6ix** [comment]
Oh okay. Thanks.
Just so you know, the windows amd64 version is not available from the GitHub downloads.
![image](https://user-images.githubusercontent.com/65610536/209575308-cdf29627-9d7b-4396-ba21-efaf816d4931.png)

**Comment by gekigek99** [comment]
yeah thanks lol I know, I realized today that it was not included in the releases.

I updated the release builder to include it.

**Comment by Chris6ix** [comment]
Okay thx
