### ISSUE TITLE
`TimeBeforeStoppingEmptyServer` keeps resetting

### ISSUE THREAD

**Issue by Chris6ix** [gekware/minecraft-server-hibernation#198]
### Current Behavior (🐛 Bug)

Setting `TimeBeforeStoppingEmptyServer` to for example 900 resets it to 30 as soon as the MS is online.
Was not an issue with `msh 2.4.10`

### Expected Behavior

`TimeBeforeStoppingEmptyServer` accepts new value and doesn't reset to default.

### Steps to Reproduce

Change `TimeBeforeStoppingEmptyServer` to something else than default
Start msh
Start the ms
Notice that the ms shuts down after 30 of no connection
Notice that `TimeBeforeStoppingEmptyServer` got reset to 30 in the config

### MSH Logs

/

### MSH-Version

2.4.11

### Operating system

Windows 10

### System architecture

amd64

### Minecraft Version

1.19.3

### Minecraft Server Software

Paper

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details.

**Comment by gekigek99** [comment]
Are you using the ptero egg or directly msh?

**Comment by Chris6ix** [comment]
msh directly

**Comment by Chris6ix** [comment]
I have tried setting it to 900 again and for some reason it works now...so I have no idea what was going on.
