### ISSUE TITLE
MSH telling me every 20 minutes in game that it's running a dev release

### ISSUE THREAD

**Issue by Chris6ix** [gekware/minecraft-server-hibernation#199]
### Current Behavior (🐛 Bug)

Every 20 minutes, I get this message in game:

![2023-01-28_00 32 48](https://user-images.githubusercontent.com/65610536/215225248-632c9f90-b1e9-441c-8329-5af594fc91d7.png)

Here is it in the console:

![image](https://user-images.githubusercontent.com/65610536/215225142-23e617f8-325c-41fb-8d2b-70d497ce64af.png)

I have no idea what the use of that is, but it's quite annoying after a while

### Expected Behavior

No message

### Steps to Reproduce

Use msh?

### MSH Logs

/

### MSH-Version

2.4.11

### Operating system

Windows 10

### System architecture

amd64

### Minecraft Version

1.19.3

### Minecraft Server Software

Paper

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details.

**Comment by Chris6ix** [comment]
Just realised that when I updated to the new config, I forgot to set the Notification settings to false 😅

**Comment by gekigek99** [comment]
I opened #200 to allow manual update notification
