### ISSUE TITLE
Suspend only works with suspendRefresh set to 10 seconds

### ISSUE THREAD

**Issue by beatstick** [gekware/minecraft-server-hibernation#201]
Hi, I really like this script, but I'd like to be able to suspend the server as it is running on a hdd and it takes over a minute to restart the server from hibernation. I have set all the options from the readme.md (server.properties, spigot.yml, etc.), but if I set suspend refresh higher than 10 seconds, the server will crash. 
I am running msh v. 2.4.11 on a debian 11 server.

If I set suspendrefresh > 10 seconds, I can enter the server exactly once and afterwards the last message from the log says: EXECUTED PROCESS TREE SUSPEND! and the server hangs. Sometimes I get an error message: 
 [error ≡≡≡ ] func1: MINECRAFT SERVER IS NOT RESPONDING! [00f20c]

10 Seconds are too short. The server wattage spikes from 10 to 14 Watts all the time. Maybe there is another workaround besides disabling suspend?

P.S.: I just saw I set the enable_autopause=true flag in server.properties, I don't know if this is a leftover from a mod or from another server freeze tool, should this be enabled or could it be the cause of freezes?

P.P.S: I tried setting autopause to false and still get the same results.

**Comment by gekigek99** [comment]
autopause is not part of msh configuration.

Unfortunately there is not workaround i can think of to disable the watchdog.

You can try to play more with other parameters, i know some isers managed to have it kinda functional.

The solution would be to write a super small mod (probably a 5 line of code mod) that disables the watchdog.

**Comment by gekigek99** [comment]
From [paper system-properties wiki](https://docs.papermc.io/paper/reference/system-properties)

`-Ddisable.watchdog=true` added in `msh-config.json` as `"StartServerParam": "-Ddisable.watchdog=true -Xmx1024M -Xms1024M"`

Disables the watchdog (and related crash)

This works only on **paper** and **purpur** (if you find some other flavours that support a similar flag report them here)

**Comment by beatstick** [comment]
I can confirm this works with paper minecraft v.1.19.3 and v. 1.19.4.

Thanks.

I think this issue can be closed now.
