### ISSUE TITLE
Listen tcp 0.0.0.0:25555: bind: address already in use

### ISSUE THREAD

**Issue by onrecc** [gekware/minecraft-server-hibernation#204]
### Current Behavior (🐛 Bug)

Does not start after building, filling config and running ./msh, just throws an error.

### Expected Behavior

It should start up and do its thing

### Steps to Reproduce

Built using GO 1.19, then filled out the config file

```
{
  "Server": {
    "Folder": "/opt/mcsmanager/daemon/data/InstanceData/8a68516513a7499fb1d44a85eecd63be",
    "FileName": "paper1.19.3.jar",
    "Version": "",
    "Protocol": 761
  },
  "Commands": {
    "StartServer": "java -jar paper1.19.3.jar nogui",
    "StartServerParam": "-Xmx1024M -Xms1024M -Dfile.encoding=UTF-8",
    "StopServer": "stop",
    "StopServerAllowKill": 30
  },
  "Msh": {
    "Debug": 3,
    "ID": "781...1da9",
    "ListenPort": 25555,
    "TimeBeforeStoppingEmptyServer": 120,
    "SuspendAllow": false,
    "SuspendRefresh": -1,
    "InfoHibernation": "                   §fserver status:\n                   §b§lHIBERNATING",
    "InfoStarting": "                   §fserver status:\n                    §6§lWARMING UP",
    "NotifyUpdate": true,
    "NotifyMessage": true,
    "Whitelist": [],
    "WhitelistImport": false
  }
}
```

ran using ./msh

### MSH Logs

![image](https://user-images.githubusercontent.com/97754680/217622007-b8f47790-d9fb-4b68-9634-8172b1b20cd1.png)

### MSH-Version

2.4.10

### Operating system

Ubuntu 22.04

### System architecture?

I386

### Minecraft Version

1.19.3 Purpur, and a Waterfall Bungeecord server (I think 1.19.3)

### Minecraft Server Software?

Other (Add to Minecraft Version)

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details.

**Comment by gekigek99** [comment]
Address already in use means that there is an other program running on the same port.

Usually its an othe rinstance of msh that you forgot to kill.

**Comment by onrecc** [comment]
Well what port should I use other than the one I use for Waterfall?

**Comment by gekigek99** [comment]
Explain better your setup please (addresses connections proxyes ecc...).

Or you can solve it by using a port different from 25555 i guess.

**Comment by onrecc** [comment]
I have a Waterfall proxy running on port 25555, a hub server running on 25565, then a couple more servers ranging from 25566-25569.

**Comment by gekigek99** [comment]
Clients connect to the waterfall proxy on port 25555?

Msh accepts clients on which port?

What is the ms server port?

**Comment by onrecc** [comment]
Players connect to the proxy on port 25555 and then get sent to the Hub which is on port 25565.

**Comment by gekigek99** [comment]
Use `netstat -tulpn | grep ':25555'` to understand which process is already listening on port 25555 and kill it.

**Comment by onrecc** [comment]
A java process is listening on port 25555 which I assume is my Waterfall proxy

**Comment by gekigek99** [comment]
Ok then change msh port.

I'll close the issue as it's not related to msh but to specific user config.

**Comment by onrecc** [comment]
What should I change the port into then if not the port that the players use to join??

**Comment by gekigek99** [comment]
Change msh port to 24444 and tell players to connect to that port

**Comment by onrecc** [comment]
Alright well then I only want it to shut down some of my servers not the whole proxy, but I assume that is not possible if it just redirects to the server you have entered in your config.

**Comment by gekigek99** [comment]
Idk... I've no experience with waterfall proxy.

There are some users that had the same problem and maybe found a workaround.

You can try and ask on the discord server.

**Comment by onrecc** [comment]
I assume you then don't have any experience running with Bungeecord either.
