### ISSUE TITLE
MSH cannot find my server.jar file with correct file path

### ISSUE THREAD

**Issue by zachlucas1** [gekware/minecraft-server-hibernation#205]
### Current Behavior (🐛 Bug)

When I start it up it says there is no such file {server.jar} or directory when starting MSH.

### Expected Behavior

I believe I put in the correct file path and it to find the file and run but that is not the case for me. Maybe I did something incorrect.

### Steps to Reproduce

I set the correct file path, Minecraft version number, and server start parameters
![Screenshot 2023-02-09 102449](https://user-images.githubusercontent.com/82626137/217891837-b8335fc1-cbac-443c-aaee-43177c8d059f.png)
![Screenshot 2023-02-09 102407](https://user-images.githubusercontent.com/82626137/217891848-aa5427e3-ce08-4c56-8fce-fe1332233241.png)
![Screenshot 2023-02-09 102227](https://user-images.githubusercontent.com/82626137/217891863-2ab4b92c-56b4-4f35-b1ed-7d2d9930143e.png)

### MSH-Version

2.4.0

### Operating system

Oracle Linux Server (ARM based and like Fedora)

### System architecture?

ARM 64 Bit

### Minecraft Version

1.19.3

### Minecraft Server Software?

Vanilla

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details.

**Comment by gekigek99** [comment]
Remember to remove the brackets lol
