### ISSUE TITLE
Make MSH watch eula.txt and toggle to the correct state when its modifyed

### ISSUE THREAD

**Issue by BolverBlitz** [gekware/minecraft-server-hibernation#207]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Currently you start msh, it will check if eula.txt exists.
It does not -> It launches MS to generate it.
Then its stuck until you restart it (At least in the Egg)

### Describe the solution you'd like.

With libs like fsnotify msh could watch the file until it was modifyed, then check if its correct and reset its state.

**Comment by gekigek99** [comment]
fixed in 0d6f6da38684c127c5a0a18a69ed679b63d56832
