### ISSUE TITLE
Automatic Queue System

### ISSUE THREAD

**Issue by BoghosDavtyan** [gekware/minecraft-server-hibernation#278]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Instead of disconnecting the player from the server and telling him to wait until the server is ready, the server will automatically redirect the player once it is prepared.

### Describe the solution you'd like.

The system connects the player to an alternative world that functions without the need for packet transfer, thus relieving the server of additional tasks. Meanwhile, the server will provide updates on its status and how soon it will be available for access. This approach is similar to the queue systems used by servers like 2B2T and Hypixel, except it involves a queue to enter the server rather than a player limit.

**Comment by giacomo-riberi** [comment]
Sounds like a great idea!

Would be able to privide the first 10kb of data exchanged while waiting in cue? To see the packets exchanged to make the info update happen on the client screen?

And provide also a way to reproduce such behavour locally to test/debug it?
