### ISSUE TITLE
Server shutting down automatically even with players connected

### ISSUE THREAD

**Issue by realairacobra** [gekware/minecraft-server-hibernation#283]
### Current Behavior (🐛 Bug)

After joining and playing for a while the server automatically shuts down

### Expected Behavior

After joining and playing for a while the server doesnt shut down until we leave

### Steps to Reproduce

Open MSH
Join the server
Play for a while
It shuts down.

### MSH Logs

2024/04/10 14:44:35.149 [info  ≡   ] checking OS support...
2024/04/10 14:44:35.149 [info  ≡   ] loading config...
2024/04/10 14:44:35.149 [info  ≡   ] reading config file: "/home/l13/minecraft-server-hibernation/msh-config.json"
2024/04/10 14:44:35.149 [info  ≡   ] msh instance file exists
2024/04/10 14:44:35.149 [info  ≡   ] msh instance loaded is healthy
2024/04/10 14:44:35.149 [info  ≡≡≡≡] setting log level to: 1
2024/04/10 14:44:35.149 [info  ≡≡≡ ] eula.txt exist and is set to true
2024/04/10 14:44:36.159 [info  ≡≡≡ ] listening for new clients connections on    0.0.0.0:25555 ...
2024/04/10 14:44:36.168 [info  ≡≡≡≡] msh (v2.5.0) is updated
2024/04/10 14:44:39.525 [info  ≡≡≡ ] MINECRAFT SERVER IS STARTING!
2024/04/10 14:45:14.731 [info  ≡≡≡ ] MINECRAFT SERVER IS ONLINE!
2024/04/10 14:45:18.115 [info  ≡≡≡ ] A CLIENT CONNECTED TO THE SERVER! (join req) - 1 active connections
2024/04/10 14:45:24.215 [info  ≡≡≡ ] A CLIENT CONNECTED TO THE SERVER! (join req) - 2 active connections
2024/04/10 14:46:24.216 [info  ≡≡≡ ] performing scheduled ms soft freeze
2024/04/10 14:46:24.423 [info  ≡≡≡ ] 2 online players - method for player count: server info
2024/04/10 14:53:30.166 [info  ≡≡≡ ] A CLIENT DISCONNECTED FROM THE SERVER! (join req) - 0 active connections
2024/04/10 14:53:30.166 [info  ≡≡≡ ] A CLIENT DISCONNECTED FROM THE SERVER! (join req) - 1 active connections
2024/04/10 14:53:30.167 [info  ≡≡≡ ] MINECRAFT SERVER IS OFFLINE!
2024/04/10 14:53:56.011 [info  ≡≡≡ ] MINECRAFT SERVER IS STARTING!
2024/04/10 14:54:31.280 [info  ≡≡≡ ] MINECRAFT SERVER IS ONLINE!
2024/04/10 14:55:11.689 [info  ≡≡≡ ] A CLIENT CONNECTED TO THE SERVER! (join req) - 1 active connections
2024/04/10 14:56:06.750 [info  ≡≡≡ ] A CLIENT CONNECTED TO THE SERVER! (join req) - 2 active connections
2024/04/10 14:57:06.751 [info  ≡≡≡ ] performing scheduled ms soft freeze
2024/04/10 14:57:06.955 [info  ≡≡≡ ] 2 online players - method for player count: server info

### MSH-Version

2.5.0

### MSH-Commit

Compiled it today without the dev branch, no clue how to find it.

### Operating system

ArcoLinuxXL

### System architecture?

AMD64

### Minecraft Version

1.20.1

### Minecraft Server Software?

Fabric

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details.

**Comment by realairacobra** [comment]
```
2024/04/10 14:44:35.149 [info ≡ ] checking OS support...
2024/04/10 14:44:35.149 [info ≡ ] loading config...
2024/04/10 14:44:35.149 [info ≡ ] reading config file: "/home/l13/minecraft-server-hibernation/msh-config.json"
2024/04/10 14:44:35.149 [info ≡ ] msh instance file exists
2024/04/10 14:44:35.149 [info ≡ ] msh instance loaded is healthy
2024/04/10 14:44:35.149 [info ≡≡≡≡] setting log level to: 1
2024/04/10 14:44:35.149 [info ≡≡≡ ] eula.txt exist and is set to true
2024/04/10 14:44:36.159 [info ≡≡≡ ] listening for new clients connections on 0.0.0.0:25555 ...
2024/04/10 14:44:36.168 [info ≡≡≡≡] msh (v2.5.0) is updated
2024/04/10 14:44:39.525 [info ≡≡≡ ] MINECRAFT SERVER IS STARTING!
2024/04/10 14:45:14.731 [info ≡≡≡ ] MINECRAFT SERVER IS ONLINE!
2024/04/10 14:45:18.115 [info ≡≡≡ ] A CLIENT CONNECTED TO THE SERVER! (join req) - 1 active connections
2024/04/10 14:45:24.215 [info ≡≡≡ ] A CLIENT CONNECTED TO THE SERVER! (join req) - 2 active connections
2024/04/10 14:46:24.216 [info ≡≡≡ ] performing scheduled ms soft freeze
2024/04/10 14:46:24.423 [info ≡≡≡ ] 2 online players - method for player count: server info
2024/04/10 14:53:30.166 [info ≡≡≡ ] A CLIENT DISCONNECTED FROM THE SERVER! (join req) - 0 active connections
2024/04/10 14:53:30.166 [info ≡≡≡ ] A CLIENT DISCONNECTED FROM THE SERVER! (join req) - 1 active connections
2024/04/10 14:53:30.167 [info ≡≡≡ ] MINECRAFT SERVER IS OFFLINE!
```
These are the logs from when

**Comment by realairacobra** [comment]
```
2024/04/10 14:44:35.149 [info ≡ ] checking OS support...
2024/04/10 14:44:35.149 [info ≡ ] loading config...
2024/04/10 14:44:35.149 [info ≡ ] reading config file: "/home/l13/minecraft-server-hibernation/msh-config.json"
2024/04/10 14:44:35.149 [info ≡ ] msh instance file exists
2024/04/10 14:44:35.149 [info ≡ ] msh instance loaded is healthy
2024/04/10 14:44:35.149 [info ≡≡≡≡] setting log level to: 1
2024/04/10 14:44:35.149 [info ≡≡≡ ] eula.txt exist and is set to true
2024/04/10 14:44:36.159 [info ≡≡≡ ] listening for new clients connections on 0.0.0.0:25555 ...
2024/04/10 14:44:36.168 [info ≡≡≡≡] msh (v2.5.0) is updated
2024/04/10 14:44:39.525 [info ≡≡≡ ] MINECRAFT SERVER IS STARTING!
2024/04/10 14:45:14.731 [info ≡≡≡ ] MINECRAFT SERVER IS ONLINE!
2024/04/10 14:45:18.115 [info ≡≡≡ ] A CLIENT CONNECTED TO THE SERVER! (join req) - 1 active connections
2024/04/10 14:45:24.215 [info ≡≡≡ ] A CLIENT CONNECTED TO THE SERVER! (join req) - 2 active connections
2024/04/10 14:46:24.216 [info ≡≡≡ ] performing scheduled ms soft freeze
2024/04/10 14:46:24.423 [info ≡≡≡ ] 2 online players - method for player count: server info
2024/04/10 14:53:30.166 [info ≡≡≡ ] A CLIENT DISCONNECTED FROM THE SERVER! (join req) - 0 active connections
2024/04/10 14:53:30.166 [info ≡≡≡ ] A CLIENT DISCONNECTED FROM THE SERVER! (join req) - 1 active connections
2024/04/10 14:53:30.167 [info ≡≡≡ ] MINECRAFT SERVER IS OFFLINE!
```
These are the logs from when i opened it until it crashed, didnt mean to mark this as completed

**Comment by owenthewizard** [comment]
I've had this happen once so far.

**Comment by gekigek99** [comment]
@realairacobra can you reproduce using loglevel 2?
would you mind sharing also the config file?
