### ISSUE TITLE
log server public IP instead of localhost when players connect [logging update]

### ISSUE THREAD

**Issue by lubocode** [gekware/minecraft-server-hibernation#49]
Currently all connection messages just say that someone wanted to connect to 127.0.0.1:25565 or in other words localhost.
This is the way the script communicates with the MC server, but for the user it would be more useful to know the IP address the script uses to communicate with the clients.
Maybe this should be added in the logging messages or perhaps even replace the 127.0.0.1:25565.

**Comment by gekigek99** [comment]
> the IP address the script uses to communicate with the clients.

what do you mean?

**Comment by lubocode** [comment]
The IP of the Host system used for communication with the MC client.
And not just any IP of the Host, but the one actually used by the client to send a message to the script.

**Comment by gekigek99** [comment]
Ok so something  on the line of `"client public IP" tried to connect to "server public IP":25555`?

**Comment by lubocode** [comment]
Yes. Though PCs can have multiple interfaces with multiple IPs, so it might be necessary to somehow figure out which one was used.

**Comment by gekigek99** [comment]
Yea but that is quite problematic to automate... This is way initially I just did in this way.  
I will do some research on the argument anyway ;)

**Comment by gekigek99** [comment]
getting the server public ip is not difficult but requires the use of an API request (which might fail)

this is an code of example to do that:

package main
```go
package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
	"net/http"
)

// json response:
// {
// 	"status": "success",
// 	"country": "xxx",
// 	"countryCode": "xxx",
// 	"region": "xxx",
// 	"regionName": "xxx",
// 	"city": "xxx",
// 	"zip": "xxx",
// 	"lat": 12.3456,
// 	"lon": 12.3456,
// 	"timezone": "America/Toronto",
// 	"isp": "Fastweb SpA",
// 	"org": "Fastweb L3 PAT NAT",
// 	"as": "ASxxxxx Fastweb SpA",
// 	"query": "xxx.xxx.xxx.xxx"
// }
type apiResponse struct {
	Query string
}

func main() {
	fmt.Println(getServerPublicIP())
}

func getServerPublicIP() string {
	req, err := http.Get("http://ip-api.com/json/")
	if err != nil {
		return err.Error()
	}
	defer req.Body.Close()

	body, err := ioutil.ReadAll(req.Body)
	if err != nil {
		return err.Error()
	}

	var res apiResponse
	json.Unmarshal(body, &res)

	return res.Query
}
```

the only problem with that is that i don't really like using an API request for this kind of thing since errors might happen and relies on an external website.

For now this issue is on hold, is someone has any idea for a workaround please report it in this issue

**Comment by TheKrafter** [comment]
I don't know that people want the IP of their servers just handed out, some people use a proxy infront of their server that could be bypassed with the actual server IP

**Comment by gekigek99** [comment]
> I don't know that people want the IP of their servers just handed out, some people use a proxy infront of their server that could be bypassed with the actual server IP

What do you mean? you think this feature is unnecessary?

**Comment by TheKrafter** [comment]
yes, i think this is either unnecessary, or should just have someone set the IP they want users to see in the config

**Comment by gekigek99** [comment]
I closed the issue because i think it's not really clear the problem and the solution (there are so many edge/peculiar cases which will make the solution unreliable).

Plus i want to focus on more important and recent stuff.
