### ISSUE TITLE
Add the possibility for server-icon-frozen to have different size and format

### ISSUE THREAD

**Issue by gekigek99** [gekware/minecraft-server-hibernation#52]
This issue derives from #30

**Comment by lubocode** [comment]
Added image dimension check for now to prevent errors with Minecraft.
2f65dd1ecff76535f7df711ec5fb35d92755d027

**Comment by gekigek99** [comment]
removed the double read on the icon file in d91e4e2

**Comment by gekigek99** [comment]
added in 9adb78d910fbaba311f3fb3dd91a5f4c6e020d52
