### ISSUE TITLE
more info for players trying to join server

### ISSUE THREAD

**Issue by BolverBlitz** [gekware/minecraft-server-hibernation#97]
**accepted EULA**  
MSH should check if EULA has been accepted, if not don´t even start the minecraft server and kick the user with something like "Eule needs to be accepted"

**Crash detection**
If a minecraft server never gets to the "Started" state MSH should chance the MOTD to like "Chrashed, do not join" so users don´t try joining all the time and create huge CPU load.

**Comment by gekigek99** [comment]
> Crash dedection: If a minecraft server never gets to the "Started" state MSH should chance the MOTD to like "Chrashed, do not join" so users don´t try joining all the time and create huge CPU load.

I was thinking more of some error message in the loading screen

**Comment by gekigek99** [comment]
issue continued in #137
